{
    "name"         : "exception",
    "url"          : "https://github.com/RealyUniqueName/Haxe-Exception",
    "license"      : "MIT",
    "tags"         : ["exception"],
    "description"  : "Base class for exceptions",
    "version"      : "0.1.3",
    "releasenote"  : "Fix 'assignin value to itself' bug when targeting python. ",
    "classPath"    : "src",
    "contributors" : ["RealyUniqueName"],
    "dependencies" : {}
}